# Generated by Django 3.1.1 on 2022-01-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='p_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
