# Generated by Django 3.1.1 on 2022-01-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_productmodel_p_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
