# Generated by Django 3.1.1 on 2022-01-29 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_productmodel_qty'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product_table',
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_app.productmodel')),
            ],
            options={
                'db_table': 'sale_table',
            },
        ),
    ]
