# Generated by Django 3.1.1 on 2022-01-29 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo_app', '0004_auto_20220129_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrderListModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'order_list_table',
            },
        ),
        migrations.CreateModel(
            name='ProductOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=30)),
                ('grand_total', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.DeleteModel(
            name='SaleModel',
        ),
        migrations.AddField(
            model_name='productorderlistmodel',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_app.productordermodel'),
        ),
        migrations.AddField(
            model_name='productorderlistmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='demo_app.productmodel'),
        ),
    ]
