# Generated by Django 3.1.1 on 2022-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_auto_20220129_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='productordermodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productordermodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
